"""create alert_content table and alert facts

Revision ID: 0b3a5da5e75d
Revises: 7a56c5bc4f4f
Create Date: 2026-09-11 15:07:36.853434

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b3a5da5e75d"
down_revision: str | Sequence[str] | None = "7a56c5bc4f4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_content",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generated_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generated_script", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("video_caption_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alert.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_content_alert_id"), "alert_content", ["alert_id"], unique=False)
    op.create_index(
        op.f("ix_alert_content_household_id"), "alert_content", ["household_id"], unique=False
    )
    # Alerts drafted before this revision have no facts object; the server
    # default backfills them with an empty one so the column can be NOT NULL.
    op.add_column(
        "alert",
        sa.Column("facts", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alert", "facts")
    op.drop_index(op.f("ix_alert_content_household_id"), table_name="alert_content")
    op.drop_index(op.f("ix_alert_content_alert_id"), table_name="alert_content")
    op.drop_table("alert_content")
    # ### end Alembic commands ###
