"""create delivery_status_callback table

Revision ID: 2dd3896f6ac9
Revises: b10ac5cd1f8a
Create Date: 2026-09-16 15:06:01.328373

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dd3896f6ac9"
down_revision: str | Sequence[str] | None = "b10ac5cd1f8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_status_callback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("delivery_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("twilio_sid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("raw_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_attempt_id"],
            ["delivery_attempt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("twilio_sid", "status", name="uq_status_callback_sid_status"),
    )
    op.create_index(
        op.f("ix_delivery_status_callback_delivery_attempt_id"),
        "delivery_status_callback",
        ["delivery_attempt_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_delivery_status_callback_delivery_attempt_id"),
        table_name="delivery_status_callback",
    )
    op.drop_table("delivery_status_callback")
    # ### end Alembic commands ###
