"""create zone and household tables

Revision ID: 8d8d7b8a1678
Revises:
Create Date: 2026-09-08 15:15:01.397052

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d8d7b8a1678"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zone",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("geo_boundary", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_zone_name"), "zone", ["name"], unique=False)
    op.create_table(
        "household",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("literacy_level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("accessibility_needs", sa.JSON(), nullable=False),
        sa.Column("preferred_channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fallback_channel_order", sa.JSON(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=False),
        sa.Column("last_known_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_household_phone_number"), "household", ["phone_number"], unique=True)
    op.create_index(op.f("ix_household_zone_id"), "household", ["zone_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_household_zone_id"), table_name="household")
    op.drop_index(op.f("ix_household_phone_number"), table_name="household")
    op.drop_table("household")
    op.drop_index(op.f("ix_zone_name"), table_name="zone")
    op.drop_table("zone")
    # ### end Alembic commands ###
