"""create delivery_attempt table

Revision ID: b10ac5cd1f8a
Revises: 0b3a5da5e75d
Create Date: 2026-09-14 15:12:14.324444

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b10ac5cd1f8a"
down_revision: str | Sequence[str] | None = "0b3a5da5e75d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_attempt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("twilio_sid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alert.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_attempt_alert_id"), "delivery_attempt", ["alert_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_attempt_household_id"), "delivery_attempt", ["household_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_attempt_twilio_sid"), "delivery_attempt", ["twilio_sid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_attempt_twilio_sid"), table_name="delivery_attempt")
    op.drop_index(op.f("ix_delivery_attempt_household_id"), table_name="delivery_attempt")
    op.drop_index(op.f("ix_delivery_attempt_alert_id"), table_name="delivery_attempt")
    op.drop_table("delivery_attempt")
    # ### end Alembic commands ###
